version: "3.7"
services:
  redis:
    image: redis:5.0-alpine
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    links:
      - redis
